annotations:
  category: Analytics
  artifacthub.io/images: |
    - name: opensearch
      image: docker.io/opensearchproject/opensearch:2.19.2
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r43
  artifacthub.io/license: MIT
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/captnbp/opensearch-dashboards
    - url: https://artifacthub.io/packages/helm/captnbp/opensearch-singlenode
  artifacthub.io/changes: |
    - kind: changed
      description: "Update Opensearch to 2.19.2"
    - kind: fix
      description: "fix: add security.existingSecret check in statefulset and jobs"
    - kind: fix
      description: "fix: extraConfig parameter not Effective Due to my_opensearch.yml not Being Loaded"
apiVersion: v2
appVersion: 2.19.2
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: OpenSearch is a distributed search and analytics engine. It is used for web search, log monitoring, and real-time analytics. Ideal for Big Data applications.
home: https://github.com/captnbp/opensearch-helm
icon: https://opensearch.org/wp-content/uploads/2025/01/opensearch_mark_default.svg
keywords:
  - opensearch
  - dashboards
  - opensearch-dashboards
  - analytics
  - monitoring
  - metrics
  - logs
maintainers:
  - email: benoit.pourre@gmail.com
    name: Benoît Pourre
name: opensearch
sources:
  - https://lab.frogg.it/captnbp/opensearch-helm
  - https://github.com/captnbp/opensearch-helm
  - https://github.com/opensearch-project
  - https://opensearch.org/
version: 3.1.1