{{- if (include "opensearch.transport.createTlsSecret" .) }}
{{- if not .Values.security.tls.transport.issuerRef.existingIssuerName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common.names.fullname" . }}-transport-ca
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: transport-ca
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  secretTemplate:
    labels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: transport-ca
      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
      {{- end }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
    {{- end }}
  subject:
    organizationalUnits:
      - {{ .Values.clusterName }}
    organizations:
      - {{ .Values.security.tls.transport.subject.organizations }}
    countries:
      - {{ .Values.security.tls.transport.subject.countries }}
  isCA: true
  commonName: {{ include "common.names.fullname" . }}-transport-ca
  secretName: {{ include "common.names.fullname" . }}-transport-ca-crt
  privateKey:
    algorithm: RSA
    size: 4096
  duration: 87600h # 10y
  issuerRef:
    name: {{ include "common.names.fullname" . }}-self-signed
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "common.names.fullname" . }}-transport
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: transport-issuer
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ca:
    secretName: {{ include "common.names.fullname" . }}-transport-ca-crt
{{- end }}
---
{{- $releaseNamespace := .Release.Namespace }}
{{- $clusterDomain := .Values.clusterDomain }}
{{- $fullname := include "opensearch.cluster_manager.fullname" . }}
{{- $serviceName := include "opensearch.cluster_manager.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "opensearch.cluster_manager.fullname" . }}-transport-crt
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: cluster_manager
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  secretTemplate:
    labels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: transport
      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
      {{- end }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
    {{- end }}
  secretName: {{ include "opensearch.cluster_manager.fullname" . }}-transport-crt
  duration: 4320h # 180d
  renewBefore: 2160h # 90d
  commonName: "{{ $fullname }}"
  subject:
    organizationalUnits:
      - {{ .Values.clusterName }}
    organizations:
      - {{ .Values.security.tls.transport.subject.organizations }}
    countries:
      - {{ .Values.security.tls.transport.subject.countries }}
  dnsNames:
    - "{{ printf "*.%s-hl.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain }}"
    - {{ printf "%s-hl.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain }}
    - "localhost"
  ipAddresses:
    - "127.0.0.1"
    - "::1"
  usages:
    - client auth
    - server auth
  privateKey:
    algorithm: {{ .Values.security.tls.transport.algorithm }}
    encoding: PKCS8
    size: {{ .Values.security.tls.transport.size }}
  issuerRef:
    name: {{ include "opensearch.security.transport.issuerName" . }}
    kind: {{ .Values.security.tls.transport.issuerRef.kind }}
    group: {{ .Values.security.tls.transport.issuerRef.group }}
---
{{- $fullname := include "opensearch.data.fullname" . }}
{{- $serviceName := include "opensearch.data.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "opensearch.data.fullname" . }}-transport-crt
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: data
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  secretTemplate:
    labels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: transport
      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
      {{- end }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
    {{- end }}
  secretName: {{ include "opensearch.data.fullname" . }}-transport-crt
  duration: 4320h # 180d
  renewBefore: 2160h # 90d
  commonName: "{{ $fullname }}"
  subject:
    organizationalUnits:
      - {{ .Values.clusterName }}
    organizations:
      - {{ .Values.security.tls.transport.subject.organizations }}
    countries:
      - {{ .Values.security.tls.transport.subject.countries }}
  dnsNames:
    - "{{ printf "*.%s-hl.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain }}"
    - {{ printf "%s-hl.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain }}
    - "localhost"
  ipAddresses:
    - "127.0.0.1"
    - "::1"
  usages:
    - client auth
    - server auth
  privateKey:
    algorithm: {{ .Values.security.tls.transport.algorithm }}
    encoding: PKCS8
    size: {{ .Values.security.tls.transport.size }}
  issuerRef:
    name: {{ include "opensearch.security.transport.issuerName" . }}
    kind: {{ .Values.security.tls.transport.issuerRef.kind }}
    group: {{ .Values.security.tls.transport.issuerRef.group }}
---
{{- $fullname := include "opensearch.coordinating.fullname" . }}
{{- $serviceName := include "opensearch.coordinating.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "opensearch.coordinating.fullname" . }}-transport-crt
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: coordinating
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  secretTemplate:
    labels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: transport
      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
      {{- end }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
    {{- end }}
  secretName: {{ include "opensearch.coordinating.fullname" . }}-transport-crt
  duration: 4320h # 180d
  renewBefore: 2160h # 90d
  commonName: "{{ $fullname }}"
  subject:
    organizationalUnits:
      - {{ .Values.clusterName }}
    organizations:
      - {{ .Values.security.tls.transport.subject.organizations }}
    countries:
      - {{ .Values.security.tls.transport.subject.countries }}
  dnsNames:
    - "{{ printf "*.%s-hl.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain }}"
    - {{ printf "%s-hl.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain }}
    - "localhost"
  ipAddresses:
    - "127.0.0.1"
    - "::1"
  usages:
    - client auth
    - server auth
  privateKey:
    algorithm: {{ .Values.security.tls.transport.algorithm }}
    encoding: PKCS8
    size: {{ .Values.security.tls.transport.size }}
  issuerRef:
    name: {{ include "opensearch.security.transport.issuerName" . }}
    kind: {{ .Values.security.tls.transport.issuerRef.kind }}
    group: {{ .Values.security.tls.transport.issuerRef.group }}
---
{{- $fullname := include "opensearch.ingest.fullname" . }}
{{- $serviceName := include "opensearch.ingest.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "opensearch.ingest.fullname" . }}-transport-crt
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ingest
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  secretTemplate:
    labels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: transport
      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
      {{- end }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
    {{- end }}
  secretName: {{ include "opensearch.ingest.fullname" . }}-transport-crt
  duration: 4320h # 180d
  renewBefore: 2160h # 90d
  commonName: "{{ $fullname }}"
  subject:
    organizationalUnits:
      - {{ .Values.clusterName }}
    organizations:
      - {{ .Values.security.tls.transport.subject.organizations }}
    countries:
      - {{ .Values.security.tls.transport.subject.countries }}
  dnsNames:
    - "{{ printf "*.%s-hl.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain }}"
    - {{ printf "%s-hl.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain }}
    - "localhost"
  ipAddresses:
    - "127.0.0.1"
    - "::1"
  usages:
    - client auth
    - server auth
  privateKey:
    algorithm: {{ .Values.security.tls.transport.algorithm }}
    encoding: PKCS8
    size: {{ .Values.security.tls.transport.size }}
  issuerRef:
    name: {{ include "opensearch.security.transport.issuerName" . }}
    kind: {{ .Values.security.tls.transport.issuerRef.kind }}
    group: {{ .Values.security.tls.transport.issuerRef.group }}
{{- end }}